version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://db:5432/badminton
      - DATABASE_USERNAME=badminton
      - DATABASE_PASSWORD=password
    depends_on:
      - db
    networks:
      - badminton-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - badminton-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=badminton
      - POSTGRES_USER=badminton
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - badminton-network

volumes:
  postgres_data:

networks:
  badminton-network:
    driver: bridge